# This file captures dependencies which are written to renv.lock

library(dplyr)
library(tidyr)
library(magrittr)
library(stringr)
library(lubridate)
library(tidyselect)
library(stats)
library(purrr)
library(magrittr)
library(tibble)
library(ncdf4)
library(utils)
library(ggplot2)
library(glue)
library(palettes)
library(viridisLite)
library(abind)
library(here)
library(EnvStats)
library(hdrcde)
library(patchwork)
library(adespatial)
