---
title: Methods
format: docx
toc: true
toc-depth: 2
number-sections: true
number-depth: 2
---

```{julia}
#| include: false

ROOT = dirname(Base.active_project())

include("$ROOT/src/count.jl")
include("$ROOT/src/presence.jl")
import .CountVariables
import .PresenceVariables

using Markdown, DataFrames, CSV

lu(x) = length(unique(x))

presencepreds = CSV.read("$ROOT/results/data/presencepreds.csv", DataFrame)
n_pres_pos = sum(presencepreds.mean .> 0.8)
n_pres_neg = sum(presencepreds.mean .< 0.2)
```

# Preamble

## Why Bayesian

The models presented below are Bayesian predictive models.
We have opted for a Bayesian approach because of ability to deal with the small number of observations for some species and the presence of outliers in these small samples.[^1]

Bayesian models are particularly well-suited for handling hierarchical data structures like the one we faced in this analysis.[^2]
Finally, carefully chosen priors help regularize estimates and thus prevent overfitting, which is essential in prediction modeling.

[^1]: [Gelman et al., 2020](https://www.cambridge.org/highereducation/books/regression-and-other-stories/DD20DD6C9057118581076E54E40C372C#overview)
[^2]: [McGlothlin & Viele, 2018](doi:10.1001/jama.2018.17977)

## Goals of analysis

```{julia}
#| echo: false

md"""
We used a two-stage model to predict the number of individuals breeding on $(lu(CountVariables.atoll.unknown.num)) unsurveyed atolls for $(lu(CountVariables.species.unknown.num)) seabird species.

In the first step, we fit a Bayesian multilevel logistic regression model to presence / absence data from $(lu(PresenceVariables.atoll.known.num)) surveyed atolls.
Next, posterior samples were used to predict the presence of $(lu(PresenceVariables.species.unknown.num)) species on $(lu(PresenceVariables.atoll.unknown.num)) unsurveyed atolls.
We combined knowledge from the literature and model predictions to compile a list of atolls for which count predictions should be made.
Including a given species *s* from a given unsurveyed atoll *a* in the list of atoll-species pairs for which count predictions were made, required that species' *s* mean predicted probability of being present on atoll *a* exceeded 80%.
In total, we made count predictions for $(nrow(presencepreds)) atoll-species pairs, as described below, of which $(n_pres_pos) were predictions of our presence model.
Conversely, the model confidently predicted the absence of $(n_pres_neg) atoll-species pairs, i.e., their mean predicted probability was below 20%.

In the second step, we fit a Bayesian multilevel regression model to log-transformed bird counts from surveyed atolls.
Lastly, posterior samples were used to predict bird counts for those atolls-species pairs for which either the literature or the predictions of our logistic model indicated that a given species was present on a given atoll.
"""
```

# Explain the model

Both the presence model and count model use the same independent variables to model presence or counts, respectively, of species $s$ of nesting type $n$ on atoll $a$, with environmental parameters $E$, in region $r$ (for full lists of these variables, see supplements?).
Species, nesting type, atoll, and region are categorical variables. 
The $A \times 6$ matrix of environmental parameters contains the results of a principal component analysis conducted on a selection of 16 environmental variables (for further detail, see supplements?).


## Presence model

Let $y_{isn}$, where $Y \in \{0, 1\}$, denote the presence of species $s$ $(s = 1, \ldots, S)$ of nesting type $n$ $(N \in \{1, 3\})$ on atoll $a$ $(a = 1, \ldots, A)$ with environmental parameters $E_{aj}$ $(J \in \{1, 6\})$ in region $r$ $(R \in \{1, 4\})$.

$$
\begin{split}
y_{asnr} &\sim \text{Bern}(\text{p}_{asnr}) \\
\text{logit}(\text{p}_{asnr}) &= \beta_{0s[r]} + \beta_{1n[s]j} \times E_{aj} \\
\beta_{0sr} &\sim \mathcal{N}(0, 1) \\
\beta_{1nj} &\sim \mathcal{N}(\bar{\beta}_{1nj}, \tau_{nj}) \\
\bar{\beta}_{1nj} &\sim \mathcal{N}(0, 0.2) \\
\tau_{nj} &\sim \text{Inv-Gamma}(3, 0.5)
\end{split}
$$

### Likelihood function

The parameter $\beta_{0sr}$ encodes the probability that species $s$ occurs in the region $r$ in which atoll $a$ is located.

The parameter $\beta_{1nj}$ encodes how environmental parameters of atoll $a$ affect the probability that species $s$ within a nesting type $n$ occurs on atoll $a$.
This effect is allowed to differ between nesting types, such that the probability that a ground nesting species occurs on atoll $a$ increases with some environmental parameter, while the probability of a tree nesting species decreases.
By partially pooling species within nesting types, we express our assumption that species from the same nesting type $n$ are similarly affected by certain environmental parameters.

### Priors

The priors of the presence model are weakly informative.
Their small variance serves to regularize the estimates and prevent overfitting where few samples are available in our hierarchical data structure.

We assume $\beta_{0sr}$, the parameter encoding regional variation in species occurence, to have the largest variation. 
It is often the case that species do not occur in one region while they are common in another.

In contrast, we assume the variation resulting from $\beta_{1nj}$, i.e., nesting type, environmental factors, and their interaction, to be much smaller than that caused by the regional variation encoded in $\beta_{0sr}$.

## Count model

Let $y_{isn}$, where $Y \in \{0, 1\}$, denote the log-transformed count of individuals of species $s$ $(s = 1, \ldots, S)$ of nesting type $n$ $(N \in \{1, 3\})$ on atoll $a$ $(a = 1, \ldots, A)$ in region $r$ $(R \in \{1, 4\})$.

$$
\begin{split}
y_{asnr} &\sim \mathcal{N}(\mu_{asnr}, \sigma) \\
\mu_{asnr} &= \beta_{0s} + \beta_{1nj} \times E_{aj} \\
\sigma &\sim \text{Inv-Gamma}(3, \sqrt{2}) \\
\beta_{0s} &\sim \mathcal{N}(\bar{\beta}_{0s}, \tau_{0}) \\
\beta_{1nj} &\sim \mathcal{N}(\bar{\beta}_{1nj}, \tau_{nj}) \\
\bar{\beta}_{0s} &\sim \mathcal{N}(M_s, 1) \\
\bar{\beta}_{1nj} &\sim \mathcal{N}(0, 1) \\
\tau_{0} &\sim \text{Inv-Gamma}(3, \sqrt{2}) \\
\tau_{1nj} &\sim \text{Inv-Gamma}(3, \sqrt{2})
\end{split}
$$

### Likelihood function

The parameter $\beta_{0s}$ encodes the abundance of species $s$ across regions by nesting regional estimates within species.
As such, $\bar{\beta}_{0s}$ is the average abundance of species $s$ across regions.
The hyperparameter on $\tau_0$ encodes the variation between regions across species.<br />
By partially pooling regions within species, we express our assumption that species $s$ forms colonies of similar size across regions.
This is unlike the presence model, where the fixed effect $\beta_{0sr}$ prevents information flow between species $s$'s estimates for different regions.

The parameter $\beta_{1nj}$ encodes how environmental parameters affect the abundance of species within a nesting type.
This effect is allowed to differ between nesting types, such that the abundance of a species of ground nesters may be positively related to some environmental parameters, while the abundance of tree nesters may be negatively related.
By partially pooling species within nesting types, we express our assumption that species from the same nesting type $n$ are similarly affected by certain environmental parameters.

### Priors

The priors of the count model are in part informed and in part weakly informed, with the intention of regularizing estimates.

The informed prior on $\bar{\beta}_{0s}$ is set to the median log-transformed count of each species.
Our choice of a species-specific prior informed by the data is due to the large differences in colony sizes across species, and the small sample sizes for some species.
While reasonable prior settings were consistently overwhelmed in species with medium to large sample size, species with small sample sizes ($n < 5$) require more careful specification of priors.
Consider how a species with small sample size and very small colony size is impacted by setting the prior to the average colony size across species: due to the small sample size, the prior skews our predictions towards the global average, which leads to poor predictions.

Our choice of the median over the mean is motivated by the presence of very few, very large colonies in some species.
In summary, the goal of the prior on $\bar{\beta}_{0s}$ is to enable our model to make reasonable and conservative predictions even for species with very small samples.
For further detail on the influence of different prior settings, see the results of the sensitivity analysis in the supplements.

The priors on $\bar{\beta}_{1nj}$ is weakly informed in that it places most probability mass on values near 0.

The priors on the variance parameters $\sigma$, $\tau_0$, and $\tau_{1nj}$ place more probability mass on higher variances than in the presence model to allow uncertain predictions where there are few data.

## Prior predictive check

We have conducted and visually inspected prior predictive checks for both models.
The prior predictive checks generated data in plausible value ranges, consistent with our prior knowledge.
For further details, see supplements.

# Computational details

## Software

We used the Julia Programming Language[^3] and most notably the Turing package ecosystem[^4] to fit, diagnose, visualize and summarize the Bayesian models presented here.
For an exhaustive list of all packages used and the versions, see the `Manifest.toml` file in the GitHub repository associated with this project.

[^3]: [Bezanson et al. 2017](https://doi.org/10.1137/141000671)
[^4]: [Ge et al. 2018](https://github.com/TuringLang/Turing.jl/blob/master/CITATION.bib)


## MCMC chain convergence

We made sure that all chains have converged by examining the $\hat{R}$ statistic for all models.
For detailed convergence diagnostics, see supplements.

## MCMC chain resolution

We made sure that all chains have high resolution by examining the effective sample size (ESS) in the bulk and tail regions of each parameter distribution.
For detailed convergence diagnostics, see supplements.

# Describe the posterior distribution

## Posterior predictive check

We have conducted posterior predictive checks to make sure that our model usefully mimics the observed data.
For further details on the posterior predictive checks, see supplements.

# Report sensitivity analysis

Sensitivity analyses were carried out for a wide range of different prior settings.
In summary, the results show that the results of the presence model are robust across different prior settings.
The same can be said for the count model, with the exception of very few species for which the small sample sizes are extremely low.
In situations with extremely small sample sizes, sensitivity to the prior is inevitable.
Thoughtful prior specification is critical in these situations, as described above.
