---
title: "map test"
output: html_document
date: "2023-11-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}

library("tidyverse")
library("sf")
library("patchwork")
library("rnaturalearth")
library("rnaturalearthdata")
library("RColorBrewer")
library("ggh4x")
library("adespatial")
library("scales")
library("ggalluvial")
library("here")
library("fst")
library("ggdensity")
library("JuliaCall")

```

```{r load data}

preds <- read.csv(here("data/allpopulations.csv"))
est <- read.csv(here("data/atoll_seabird_global_popestimates.csv"))
envs <- read.csv(here("data/seabird_atolls_envs.csv"))
nest <- read.csv(here("data/seabird_filterconditions.csv"))
mpa <- read.csv(here("data/mpa_polygons.csv"))

# turn into factors
envs <- envs %>% select(atoll, region, lat, long, land_area_sqkm) %>% mutate(across(1:2, as.factor))
preds <- preds %>% select(atoll, species, nbirds) %>% mutate(across(1:2, as.factor))
nest <- nest %>% select(!filtercondition) %>% mutate(across(1:3, as.factor))
mpa$mpa <- as.factor(mpa$mpa)

# turn predicted abundances into whole numbers
preds$nbirds <- round(preds$nbirds,0)

# convert longitudes for 'sf' format
envs$long <- ifelse(envs$long < 0, envs$long+360, envs$long)
mpa$long <- ifelse(mpa$long < 0, mpa$long+360, mpa$long)
```


```{r prepare data frames for plotting}

# add 'empty' atolls to count pred data frame
dat <- left_join(envs, preds, by = "atoll") %>% mutate(nbirds = replace_na(nbirds, 0))

# convert long format into atoll x species matrix for beta-diversity computation
matrix <- dat %>% pivot_wider(names_from = species, values_from = nbirds, values_fill = 0) %>% 
                    select(!"NA") %>% as.data.frame()
rm(dat) # no longer needed, keep tidy


# calculate local contribution to beta diversity (LCBD) [and species contribution to beta diversity (SCBD)]
beta.atoll <- matrix[c(which(rowMeans(matrix[,-c(1:5)]) > 0)),-c(1:5)] %>% 
                beta.div(., method = "percentdiff", sqrt.D = TRUE, samp = FALSE)
beta <- beta.atoll$LCBD %>% as.data.frame()
beta$atoll <- matrix[c(which(rowMeans(matrix[,-c(1:5)]) > 0)),]$atoll
colnames(beta)[1] <- "lcbd"
rm(beta.atoll) # no longer needed, keep tidy

# Richness differences and species turnover
comp.atoll <- matrix[c(which(rowMeans(matrix[,-c(1:5)]) > 0)),-c(1:5)] %>% beta.div.comp(., coef = "J", quant = FALSE)


# add seabird metadata and calculate atoll-wise biomass per species
comb <- matrix %>% pivot_longer(!c(atoll, region, lat, long, land_area_sqkm), names_to = "species", values_to = "nbirds")
comb$species <- as.factor(comb$species)
comb <- comb %>% left_join(., nest, by = "species") %>% as.data.frame()

# calculate total N and P input in per year and per seabird and atoll using 
# https://doi.org/10.1038/s41467-017-02446-8 and https://doi.org/0.1016/j.envpol.2004.02.008

F_nc <- 0.036 #average N content of seabird diet in g N g^-1
F_pc <- 0.006 #average P content of seabird diet in g P g^-1
F_ec <- 6.5 #average energy content of seabird diet kJ g^-1
A_eff <- 0.8 #kJ obtained by the bird per kJ consumed

# ADULTS:
# calculate basal metabolic rate for adults (kJ bird^-1 day^-1)
comb$BMR <- 2.3*comb$bodymass^0.774

# calculate field metabolic rate for adults (kJ bird^-1 day^-1)
comb$AMR <- 4*comb$BMR

# calculate total daily N and P excreted (g N or g P bird^-1 day^-1)
comb$dailyN <- (comb$AMR*F_nc)/(F_ec*A_eff)
comb$dailyP <- (comb$AMR*F_pc)/(F_ec*A_eff)
  
# extrapolate for breeding season and colony attendance
comb$seasonalN <- comb$dailyN * comb$days_at_colony * comb$time_at_colony
comb$seasonalP <- comb$dailyP * comb$days_at_colony * comb$time_at_colony

# extrapolate for colony size
comb$adultN <- comb$seasonalN*comb$nbirds
comb$adultP <- comb$seasonalP*comb$nbirds

# CHICKS:
# calculate metabolic rate for chicks (kJ bird^-1 year^-1)
comb$E_rearing <- 28.43*comb$fledgling_mass^1.06

comb$chickN <- ((comb$E_rearing*F_nc)/(F_ec*A_eff))*(comb$prod_per_pair/2)
comb$chickP <- ((comb$E_rearing*F_pc)/(F_ec*A_eff))*(comb$prod_per_pair/2)

comb$chickN <- comb$chickN*comb$nbirds
comb$chickP <- comb$chickP*comb$nbirds

# Add up adult and chick excretion
comb$excretedN <- comb$adultN + comb$chickN
comb$excretedP <- comb$adultP + comb$chickP

# convert g to kg
comb$excretedN <- comb$excretedN/1000
comb$excretedP <- comb$excretedP/1000

# calculate total bird biomass
comb$biomass <- comb$nbirds*comb$bodymass

# drop unneeded columns after computation
comb <- comb %>% select(!c(bodymass, nestingtype, BMR, AMR, dailyN, dailyP, seasonalN, seasonalP,
                           adultN, adultP, chickN, chickP, E_rearing, prod_per_pair, fledgling_mass))


# summarize atoll-wise,
atoll <- comb %>% group_by(atoll, region, lat, long, land_area_sqkm) %>% summarise(nspec = sum(nbirds > 0),
                                                                                  nbirds = sum(nbirds),
                                                                                  totbiomass = sum(biomass),
                                                                                  totN = sum(excretedN),
                                                                                  totP = sum(excretedP)) %>%
                                                                                                as.data.frame()

atoll <- atoll %>% left_join(., beta, by = "atoll") %>% mutate(lcbd = replace_na(lcbd, 0))


# summarize species-wise
spec <- comb %>% group_by(species, group) %>% summarise(nbirds = sum(nbirds),
                                                 totbiomass = sum(biomass),
                                                 totN = sum(excretedN),
                                                 totP = sum(excretedP)) %>% as.data.frame() 

# calculate proportion contribution to global population
spec <- left_join(spec, est, by = "species")

spec$ratios <- ifelse(is.na(spec$Otero) == FALSE, spec$nbirds*1/spec$Otero,
            ifelse(is.na(spec$HBW) == FALSE, spec$nbirds*1/spec$HBW, 
              ifelse(is.na(spec$birdlife_max) == TRUE, spec$nbirds*1/spec$birdlife_min,
                      spec$nbirds*1/spec$birdlife_max)))

spec <- spec %>% select(c(species, group, nbirds, totbiomass, totN, totP, ratios))
spec$species <- as.factor(spec$species)

```


```{r base map}
mapWorld <- ne_countries(scale = "medium", returnclass = "sf")
mapCoast <- ne_coastline(scale = "medium", returnclass = "sf")

spat.mpa <- mpa %>% st_as_sf(., coords = c("long", "lat"), crs = 4326)
coords.mpa <- spat.mpa %>% st_coordinates(extract())

mpa.areas <-  geom_polygon(inherit.aes = FALSE, data = spat.mpa, 
                aes(x = coords.mpa[,1], y = coords.mpa[,2], group = mpa),
                color = "#1B57A6",
                fill = "#1B57A6",
                alpha = 0.45,
                linewidth = 0.15)

# create map layer
map <- ggplot() + 
  geom_sf(data = mapWorld, fill = "#EBE3D5", color = NA) +
  geom_sf(data = mapCoast, linewidth = 0.15) +
  coord_sf(xlim = c(46.5, 265),
           ylim = c(-30, 30)) +
  theme_classic() +
  geom_segment(aes(x = 36.2, xend = 36.2, y = -30.1, yend = 30.1), linewidth = 0.8) +
  geom_segment(aes(x = 49.9, xend = 250.1, y = -33, yend = -33), linewidth = 0.8) +
  theme(
    axis.title = element_blank(),
    axis.line = element_blank(),
    axis.text = element_text(size = 11),
    axis.ticks = element_line(linewidth = 0.8),
    title = element_text(size = 13),
    legend.text = element_text(size = 9),
    legend.background = element_rect(color = "black", fill = "white"))

# set up base structure aesthetics for boxplots
boxplotaesth <- theme_classic() +
                theme(
                    legend.position = "none",
                    axis.title.x = element_blank(),
                    axis.ticks.x = element_blank(),
                    axis.text.x = element_blank(),
                    axis.text.y = element_text(size = 11),
                    axis.title.y = element_text(size = 12)
                    )

```

```{r abundance and richness}

# total bird numbers 
spat.1a <- atoll %>% arrange(nbirds) %>%  st_as_sf(., coords = c("long", "lat"), crs = 4326)
coords.1a <- spat.1a %>% st_coordinates(extract())

p1a <- map + 
  geom_point(data = spat.1a,
             aes(x = coords.1a[,1], y = coords.1a[,2], colour = log10(nbirds+1)), 
             size = 1.1, shape = 21, alpha = 0.9, stroke = 1.9) +
  scale_colour_gradientn(colours = c("#fbe725", "#3dbc74", "#306b84","black"),
                         values = c(1.0, 0.5, 0.1, 0),
                         name = "log(abundance)") +
  ggtitle("a. population size") +
  theme(legend.position = "none")

# species richness
spat.2a <- atoll %>% arrange(nspec) %>%  st_as_sf(., coords = c("long", "lat"), crs = 4326)
coords.2a <- spat.2a %>% st_coordinates(extract())

p2a <- map + 
  geom_point(data = spat.2a,
             aes(x = coords.2a[,1], y = coords.2a[,2], colour = nspec), 
             size = 1.1, shape = 21, alpha = 0.9, stroke = 1.9) +
  scale_colour_gradientn(colours = c("#fbe725", "#3dbc74", "#306b84","black"),
                         values = c(1.0, 0.3, 0.05, 0),
                         name = "Species richness") +
  ggtitle("b. diversity") +
  theme(legend.position = "none")

# dissimilarity
spat.3a <- atoll %>% st_as_sf(., coords = c("long", "lat"), crs = 4326)
coords.3a <- spat.3a %>% st_coordinates(extract())

p3a <- map +
  geom_point(data = spat.3a,
             aes(x = coords.3a[,1], y = coords.3a[,2], colour = lcbd),
             size = 1.1, shape = 21, alpha = 0.9, stroke = 1.9) +
   scale_colour_gradientn(colours = c("#fbe725", "#3dbc74", "#306b84","black"),
                         values = c(1, 0.65, 0.001, 0),
                         name = "LCBD") +
  ggtitle("c. compositional distinctness of atolls") +
  theme(legend.position = "none")


# boxplot abundance
p1b <- ggplot(data = atoll[which(atoll$nbirds > 0), ], aes(x = "identity", y = nbirds)) +
  geom_violin(fill = "#EBEBEB", alpha = 0.5) +
  geom_jitter(aes(colour = log(nbirds+1)), width = 0.15, size = 1.5) +
  geom_boxplot(fill = "#EBEBEB", width = 0.1, alpha = 0.5, outlier.shape = NA) +
  scale_y_continuous(trans = "log",
                     breaks = c(10, 100, 1000, 10000, 100000, 1000000, 10000000),
                     labels = scales::comma) +
  scale_colour_gradientn(colours = c("#fbe725", "#3dbc74", "#306b84","black"),
                         values = c(1.0, 0.5, 0.1, 0)) +
  guides(x = "axis_truncated", y = guide_axis_truncated(trunc_lower = 10, trunc_upper = 1000000)) +
  ylab("abundance") +
  geom_hline(yintercept = 13200, linetype = "dotted", linewidth = 0.5) + 
  annotate("text", label = "B3b (A4iii)", x = 1.4, y = 25000, size = 3, fontface = "italic") +
  boxplotaesth

# boxplot richness
p2b <- ggplot(data = atoll, aes(x = "identity", y = nspec)) +
  geom_violin(fill = "#EBEBEB", alpha = 0.5) +
  geom_jitter(aes(colour = nspec), width = 0.15, size = 1.5) +
  geom_boxplot(fill = "#EBEBEB", width = 0.1, alpha = 0.5, outlier.shape = NA) +
  scale_colour_gradientn(colours = c("#fbe725", "#3dbc74", "#306b84","black"),
                         values = c(1.0, 0.3, 0.05, 0)) +
  scale_y_continuous(breaks = c(0, 5, 10, 15, 19)) +
  guides(x = "axis_truncated", y = guide_axis_truncated(trunc_lower = 0, trunc_upper = 19)) +
  ylab("species richness") +
  boxplotaesth

# boxplot lcbd
p3b <- ggplot(data = atoll[which(atoll$nbirds > 0), ], aes(x = "identity", y = lcbd)) +
  geom_violin(fill = "#EBEBEB", alpha = 0.5) +
  geom_jitter(aes(colour = lcbd), width = 0.15, size = 1.5) +
  geom_boxplot(fill = "#EBEBEB", width = 0.1, alpha = 0.5, outlier.shape = NA) +
  scale_colour_gradientn(colours = c("#fbe725", "#3dbc74", "#306b84","black"),
                         values = c(1, 0.65, 0.001, 0)) +
  scale_y_continuous(breaks = c(0.0026, 0.0037, 0.0048, 0.0059)) +
  guides(x = "axis_truncated", y = guide_axis_truncated(trunc_lower = 0.0026, trunc_upper = 0.0059)) +
  ylab("LCBD") +
  boxplotaesth

pmapbox <- p1a+p1b+p2a+p2b+p3a+p3b+plot_layout(widths = c(3,1,3,1,3,1), nrow = 3, ncol = 2)

#ggsave(pmapbox, filename = "fig_pop-ric-lcbd.svg", dpi = 300, width = 210, height = 170, units = "mm")

```


```{r bird populations}
seabirdnames <- spec[,1] %>% as.data.frame()
colnames(seabirdnames) <- "species"
seabirdnames$common.names <- c("Blue-grey Noddy", "Black Noddy", "Brown Noddy", "Lesser Noddy",
                               "Wedge-Tailed Shearwater", "Bulwer's Petrel", "Lesser Frigatebird", "Great Frigatebird",
                               "White Tern", "Tristram's Storm-Petrel", "Caspian Tern", "Polynesian Storm-Petrel",
                               "Bridled Tern", "Sooty Tern", "Grey-backed Tern", "White-tailed Tropicbird", 
                               "Red-tailed Tropicbird", "Short-tailed Albatross", "Laysan Albatross", 
                               "Black-footed Albatross", "Phoenix Petrel", "Herald Petrel", "Bonin Petrel",
                               "Kermadec Petrel", "Murphy's Petrel", "Tropical Shearwater", "Christmas Shearwater",
                               "Roseate Tern", "Black-naped Tern","Australian Fairy Tern", "Saunder's Tern",
                               "Masked Booby", "Nazca Booby", "Brown Booby", "Red-footed Booby", "Lesser Crested Tern",
                               "Greater Crested Tern") %>%   
                                  as.factor()
  
spec <- left_join(spec, seabirdnames, by = "species")

spec$group <- factor(spec$group, levels = c("albatros", "booby", "frigatebird", "tubenose", "tern", "tropicbird"))

p11 <- ggplot(data = spec, aes(x = ratios*100, y = reorder(common.names, ratios), fill = group)) +
            geom_bar(stat = "identity", color = "black", width = 0.8, linewidth = 0.5) +
            annotate("rect", xmin = 25, xmax = 50, ymin = 0, ymax = 37, fill = "#eeeeee") +
            annotate("rect", xmin = 50, xmax = 75, ymin = 0, ymax = 37, fill = "#dddddd") +
            annotate("rect", xmin = 75, xmax = 95, ymin = 0, ymax = 37, fill = "#cccccc") +
            annotate("rect", xmin = 95, xmax = 100, ymin = 0, ymax = 37, fill = "#bbbbbb") +
            geom_bar(stat = "identity", color = "black", width = 0.8, linewidth = 0.5) +
            scale_fill_viridis_d(aesthetics = "fill", option = "mako",
                                 labels = c("Albatross", "Booby", "Frigatebird", "Petrel/Shearwater", "Tern", "Tropicbird")
            ) +
              guides(x = "axis_truncated", y = "axis_truncated", 
                   fill = guide_legend(byrow = TRUE)) +
            xlab("% of global population") +
            theme_classic() +
            theme(
              axis.title.y = element_blank(),
              axis.line.y = element_blank(),
              axis.ticks.y =element_blank(),
              axis.text.y = element_text(margin = margin(r = -8), size = 10), 
              axis.text.x = element_text(size = 11),
              axis.title.x = element_text(size = 12),
              legend.title = element_blank(),
              legend.position = c(0.7, 0.2),
              legend.text = element_text(size = 9),
              legend.spacing.y = unit(1, "mm"))

  
#ggsave(p11, filename = "fig_proportion_species_global.svg", dpi = 300, width = 105, height = 150, units = "mm")

```



````{r nutrient inputs}

pnut.a <- ggplot(data = atoll[which(atoll$nbirds > 0),], aes(x = "identity", y = totN)) +
            geom_violin(fill = "#EBEBEB", alpha = 0.5) +
            geom_jitter(aes(colour = totN), width = 0.15, size = 1.5) +
            geom_boxplot(fill = "#EBEBEB", width = 0.1, alpha = 0.5, outlier.shape = NA) +
            scale_y_continuous(trans = "log10", labels = scales::comma,
                               breaks = c(1, 10, 100, 1000, 10000, 100000, 1000000)) +
            scale_colour_gradientn(colours = c("#fbe725", "#3dbc74", "#306b84", "black"),
                                   values = c(1, 0.001, 0.0001, 0)) +
            ylab(expression(paste("imported nitrogen per atoll [kg N  ", year^-1,"]"))) +
            ggtitle("a. atoll-wise import") +
            guides(y = guide_axis_truncated(trunc_lower = 1, trunc_upper = 1000000)) +
            boxplotaesth +
            theme(axis.line.x = element_blank())

pnut.c <- ggplot(data = atoll[which(atoll$nbirds > 0),], aes(x = "identity", y = totP)) +
            geom_violin(fill = "#EBEBEB", alpha = 0.5) +
            geom_jitter(aes(colour = totP), width = 0.15, size = 1.5) +
            geom_boxplot(fill = "#EBEBEB", width = 0.1, alpha = 0.5, outlier.shape = NA) +
            scale_y_continuous(trans = "log10", labels = scales::comma,
                               breaks = c(1, 10, 100, 1000, 10000, 100000, 100000)) +
            scale_colour_gradientn(colours = c("#fbe725", "#3dbc74", "#306b84", "black"),
                                   values = c(1, 0.001, 0.0001, 0)) +
            ylab(expression(paste("imported phosphorous per atoll [kg P ", year^-1,"]"))) +
            ggtitle("a. phosphorous import") +
            guides(y = guide_axis_truncated(trunc_lower = 1, trunc_upper = 100000)) +
            boxplotaesth +
            theme(axis.line.x = element_blank())


nutrientinput <- comb[comb$species %in% c("Onychoprion_fuscatus", "Sula_sula", "Sula_leucogaster",
                                          "Fregata_ariel", "Thalasseus_bergii", "Sula_dactylatra",
                                          "Anous_minutus", "Anous_stolidus", "Fregata_minor", "Phaethon_rubricauda",
                                          "Gygis_alba", "Onychoprion_lunatus", "Sterna_sumatrana", "Anous_tenuirostris",
                                          "Phaethon_lepturus"),]

nutrientinput <- left_join(nutrientinput, seabirdnames, by = "species")

pnut.b <- ggplot(data = nutrientinput[which(nutrientinput$nbirds > 0),],
                 aes(y = reorder(common.names, excretedN), x = excretedN, fill = group)) +
            geom_boxplot() +
            scale_x_continuous(trans = "log10", labels = scales::comma) + 
            scale_fill_viridis_d(aesthetics = "fill", option = "mako") +
            theme_classic() +
            xlab(expression(paste("imported nitrogen per colony [kg N ", year^-1,"]"))) +
            guides(x = guide_axis_truncated(trunc_lower = 1, trunc_upper = 1000000), y = "axis_truncated") +
            ggtitle("b. keystone importers") +
            theme(
                  legend.position = "none",
                  axis.text = element_text(size = 11),
                  axis.title.x = element_text(size = 12),
                  axis.title.y = element_blank()
                  )

pnut.d <- ggplot(data = nutrientinput[which(nutrientinput$nbirds > 0),],
                 aes(y = reorder(common.names, excretedP), x = excretedP, fill = group)) +
            geom_boxplot() +
            scale_x_continuous(trans = "log10", labels = scales::comma,
                               breaks = c(1, 100, 1000, 100000)) + 
            scale_fill_viridis_d(aesthetics = "fill", option = "mako") +
            theme_classic() +
            xlab(expression(paste("imported phosphorous per colony [kg P ", year^-1,"]"))) +
            guides(x = guide_axis_truncated(trunc_lower = 1, trunc_upper = 100000), y = "axis_truncated") +
            ggtitle("b. keystone importers") +
            theme(
                  legend.position = "none",
                  axis.text = element_text(size = 11),
                  axis.title.x = element_text(size = 12),
                  axis.title.y = element_blank()
                  )

colonywise <- comb %>% group_by(atoll, group) %>% summarise(totN = sum(excretedN),
                                                            totP = sum(excretedP)) %>% as.data.frame()
colonywise$group <- factor(colonywise$group,
                           levels = c("tropicbird", "tubenose", "frigatebird", "tern", "booby", "albatros"))


pnut.e <- ggplot(data = colonywise[which(colonywise$totN > 0), ], 
                 aes(y = group, x = totN, fill = group)) +
              geom_boxplot() +
              scale_x_continuous(trans = "log10",
                                 breaks = c(0.1, 1, 10, 100, 1000, 10000, 100000, 1000000),
                                 labels =  ~ ifelse(.x < 1, label_number(accuracy = .1)(.x),
                                                            label_number(accuracy = 1)(.x))) + 
              scale_y_discrete(
              labels = c("Tropicbirds", "Petrels &\n Shearwater", "Frigatebirds" , "Terns", "Boobies", "Albatross")) +
              scale_fill_manual(values = c("#DEF5E5FF", "#3497A9FF", "#395D9CFF", "#60CEACFF", "#382A54FF", "#0B0404FF"))+
              theme_classic() +
              xlab(expression(paste("imported nitrogen per atoll-colony [kg N ", year^-1,"]"))) +
              guides(x = guide_axis_truncated(trunc_lower = 0.1, trunc_upper = 1000000), y = "axis_truncated") +
              ggtitle("b. keystone importers") +
              theme(
                    legend.position = "none",
                    axis.text.x = element_text(size = 11, angle = 30, vjust = 0.8),
                    axis.text.y = element_text(size = 11),
                    axis.title.x = element_text(size = 12),
                    axis.title.y = element_blank()
                    )

pnutrientsN <- pnut.a + pnut.e + plot_layout(widths = c(1, 1.3))
pnutrientsP <- pnut.c + pnut.d + plot_layout(widths = c(1, 1.3))

ggsave(pnutrientsN, filename = "fig_nutrient_import.svg", dpi = 300, width = 210, height = 85, units = "mm")

```


```{r significant breeding sites}

atollw <- left_join(comb, est, by = "species")

atollw$atoll.ratios <- ifelse(is.na(atollw$Otero) == FALSE, atollw$nbirds*1/atollw$Otero,
                          ifelse(is.na(atollw$HBW) == FALSE, atollw$nbirds*1/atollw$HBW, 
                            ifelse(is.na(atollw$birdlife_max) == TRUE, atollw$nbirds*1/atollw$birdlife_min,
                              atollw$nbirds*1/atollw$birdlife_max)))

atollw$species <- as.factor(atollw$species)

atollw <- atollw %>% select(!c(biomass, birdlife_min, birdlife_max, HBW, Otero))

# subset only for largest value per atoll
atollmax <- atollw %>% group_by(atoll, lat, long) %>% summarise(atoll.ratios = max(atoll.ratios)) %>% as.data.frame()
atollmax$cuts <- cut(atollmax$atoll.ratios,
                   breaks = c(0, 0.01, 0.10, 0.25, 0.50, 0.70, 1),
                   labels = c("<1%", "1-10%", "10-25%", "25-50%", "50-70%", ">70%"))

atollmax[is.na(atollmax$cuts),]$cuts <- "<1%"

atollmax <- atollmax %>% arrange(cuts)

spatw <- st_as_sf(atollmax, coords = c("long", "lat"), crs = 4326)
coordsw <- spatw %>% st_coordinates(extract())

p10 <- map +
  geom_point(data = spatw,
             aes(x = coordsw[,1], y = coordsw[,2], colour = cuts), 
             size = 1.1, shape = 21, alpha = 0.9, stroke = 1.9) +
  scale_colour_manual(values = c("#ECEE81","#7ED7C1", "#BEADFA", "#DC8686", "#B06161", "#D10015")) +
  ggtitle("Single atoll contribution to global populations") +
  theme(
    legend.title = element_blank())

# ggsave(p10, filename = "fig_atollwise_contribution_atoll_glob_NO-ICONS.svg",
#       dpi = 300, width = 210, height = 100, units = "mm")

```

```{r species heatmaps}

method_julia <- function(h = NULL, adjust = c(1, 1)) {
    # Force evaluation of function arguments to make sure they're captured
    force(h)
    force(adjust)

    # Set up Julia and KernelDensity
    julia_setup()
    julia_command("using KernelDensity")

    # Return closure with format required by get_hdr()
    function(data, n, rangex, rangey) {
        if (is.null(h)) {
            h <- c(MASS::bandwidth.nrd(data$x), MASS::bandwidth.nrd(data$y))
        }
        h <- h * adjust
        julia_assign("data", data)
        julia_assign("h", h)
        julia_assign("n", as.integer(n))
        julia_assign("rangex", rangex)
        julia_assign("rangey", rangey)
        julia_command("kdeout = kde((data.x, data.y); npoints=(n,n), boundary=((rangex[1], rangex[2]), (rangey[1], rangey[2])), bandwidth=(h[1],h[2]))")
        x <- julia_eval("kdeout.x")
        y <- julia_eval("kdeout.y")
        fhat <- julia_eval("kdeout.density")
        df <- expand.grid(x = x, y = y)
        df$fhat <- as.vector(fhat)
        df
    }
}

foraging <- read_fst(here("results/data/foraging.fst"))

spatspec <- st_as_sf(foraging, coords = c("adjlong", "adjlat"), crs = 4326)

coordspec <- spatspec %>% st_coordinates(extract())

map + 
  geom_hdr(aes(x = coordspec[, 1], y = coordspec[, 2]),
           xlim = c(0, 250),
           method = method_julia(adjust = 1 / 5000),
           probs = c(0.25, 0.5, 0.75, 0.9, 0.95, 0.97, 0.98),
           fill = "#A71B1B",
           color = NA,
           ) +
  geom_point(aes(x = coordspec[,1], y = coordspec[,2]), alpha=0.2) +
  geom_sf(data = mapWorld, fill = "#EBE3D5", color = NA) +
  geom_sf(data = mapCoast, linewidth = 0.15) +
  coord_sf(xlim = c(46.5, 265),
           ylim = c(-30, 30)) +
  theme_classic() +
  geom_segment(aes(x = 36.2, xend = 36.2, y = -30.1, yend = 30.1), linewidth = 0.8) +
  geom_segment(aes(x = 49.9, xend = 250.1, y = -33, yend = -33), linewidth = 0.8) +
  theme(
    axis.title = element_blank(),
    axis.line = element_blank(),
    axis.text = element_text(size = 11),
    axis.ticks = element_line(linewidth = 0.8),
    title = element_text(size = 13),
    legend.position = "none") +
  mpa.areas
```

```{r nmds}

library("vegan")
# tutorial: https://uw.pressbooks.pub/appliedmultivariatestatistics/chapter/nmds/

nmds <- metaMDS(comm = matrix[,-1],
                distance = "bray",
                engine = "monoMDS",
                weakties= FALSE, #do not allow that identical observations are plotted at different coordinates
                k = 3,
                maxit = 300,
                try = 40,
                trymax = 100)

nmds$stress

gof <- goodness(object = nmds)

plot(nmds, display = "sites", type = "none")
  points(nmds, display = "sites",
  cex = 2*gof/mean(gof))
  

plot(nmds$diss, nmds$dist)
plot(vegdist(matrix[,-1]), dist(scores(nmds, "sites")))

stressplot(object = nmds, lwd = 5)

nmds.point <- data.frame(nmds$points)
nmds.point$atoll <- matrix$atoll

nmds.point <- left_join(nmds.point, envs, by = "atoll")

ggplot(nmds.point, aes(x = MDS1, y = MDS2, colour = region)) +
  geom_point(size = 1.8, shape = 21, alpha = 0.9, stroke = 2.5) +
  theme_classic()

sp <- wascores(x = nmds$points, w = matrix[,-1], expand = TRUE) %>% as.data.frame()

ggplot(nmds.point, aes(x = MDS1, y = MDS2)) +
  geom_point(aes(colour = region),size = 1.8, shape = 21, alpha = 0.9, stroke = 2.5) +
  #geom_text(data = sp, label = rownames(sp)) +
  theme_classic()

```

```{r distance decay model}

library("betapart")

latlong <- left_join(matrix[,1], envs, by = "atoll") %>% as.data.frame()
latlong$long <- ifelse(latlong$long < 0, latlong$long+360, atoll.sum$long) # convert longitude

spat.dist <- dist(latlong[,c(3:4)], method = "euclidean")

dissim.atoll <- beta.pair.abund(matrix[,-1])$beta.bray.bal

plot(spat.dist, dissim.atoll, ylim = c(0,1), xlim = c(0, max(spat.dist)))

decay.exp <- decay.model(y = dissim.atoll, x = spat.dist,
                         y.type="dissimilarities", model.type="pow", perm=100)

```


```{r atoll contribution to individual species}

top3 <- atollw %>% group_by(species) %>% arrange(desc(atoll.ratios)) %>% slice(1:3) %>% as.data.frame()

top3 %>% count(atoll, sort = TRUE)

``` 


```{r alluvial plot}

# get species with more than 60% of global population on atolls
key.spec <- spec %>% filter(ratios > 0.6) %>% select(species) %>% pull(species) %>% as.vector()

# subset for each species the four atolls with the largest colony sizes
key.atolls <- atollw %>% group_by(species) %>% arrange(desc(atoll.ratios)) %>% slice(1:4) %>% as.data.frame()

# add total atoll population size per species and global ratio
key.atolls <- key.atolls %>% left_join(., spec %>% select(species, nbirds, ratios), by = "species")

key.atolls <- rename(key.atolls, nbirds = nbirds.x)
key.atolls <- rename(key.atolls, total.atoll.pop = nbirds.y)
key.atolls <- rename(key.atolls, global.ratios = ratios)

# select only key species (i.e., with >60% global population on atolls)
key.atolls <- key.atolls %>% filter(species %in% key.spec)

# calculate combined contribution of all other (not key) atolls to seabird population size
others <- key.atolls %>% group_by(species, total.atoll.pop) %>% summarise(combined = sum(nbirds)) %>% 
            mutate(nbirds = total.atoll.pop - combined) %>% mutate(atoll.ratios = nbirds*1/total.atoll.pop) %>%   
            as.data.frame()

others$atoll <- "rest"
others <- others %>% select(c(species, nbirds, atoll.ratios, atoll))
others$atoll <- as.factor(others$atoll)

# add global proportion 
others <- others %>% left_join(., spec %>% select(species, group, ratios), by = "species")
others <- rename(others, global.ratios = ratios)

# add other atolls to key atolls for alluvium plot
key.atolls <- key.atolls %>% bind_rows(., others)

# get common names
key.atolls <- key.atolls %>% left_join(., spec %>% select(species, common.names), by = "species")


p12 <- ggplot(data = key.atolls, aes(axis1 = reorder(common.names, 1/global.ratios), axis2 = atoll, y = atoll.ratios)) +
  geom_alluvium(aes(fill = common.names)) +
  geom_stratum() +
  geom_text(stat = "stratum",
            aes(label = after_stat(stratum))) +
  scale_x_discrete(limits = c("species", "atoll"),
                   expand = c(0.1, 0.05)) +
  geom_label(stat = "stratum", aes(label = after_stat(stratum))) +
  scale_fill_viridis_d(option = "mako") +
  theme_classic() +
  theme(
    legend.position = "none",
    axis.text = element_blank(),
    axis.line = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank()
  ) +
  annotate(geom = "text", x = 2, y = 7.2, label = "n = 19 key atolls", size = 4.2) +
  annotate(geom = "text", x = 1, y = 7.2, label = "seabirds >60% of \n global population on atolls", size = 4.2)

#ggsave(p12, filename = "fig_keyatolls.svg", dpi = 300, width = 210, height = 160, units = "mm")

```



```{r foraging space}

library("EnvStats")
library("fields")


km2d <- function(km, base.latitude) {
  out <- NULL
  for (i in 1:length(base.latitude)) {
    one.degree.dist <- fields::rdist.earth(matrix(c(0, base.latitude[i]), ncol = 2), 
                                           matrix(c(1, base.latitude[i]), ncol = 2), miles = FALSE) %>% as.integer()
    temp <- km[i] / one.degree.dist
    out <- rbind(out, temp)
  }
    return(out)
}

meanmaxdist <- 240 #km
sdmaxdist <- 30 # km


dist <- rgevd(n = 280, location = meanmaxdist-sdmaxdist, scale = sdmaxdist, shape = 0.8) %>% as.vector()
direct <- runif(280, 0, 360) %>% as.vector()

plot(density(dist))

scatter <- as.data.frame(cbind(dist, direct))
scatter$lat <- envs$lat
scatter$long <- envs$long

# calculate km lat and km long dist
scatter$add.lat.km <- cos((scatter$direct*pi)/180) * scatter$dist # latitude, 
scatter$add.long.km <- sin((scatter$direct*pi)/180) * scatter$dist # longitude

# convert km into decimal degree lat and long distance
scatter$add.lat.deg <- km2d(scatter$add.lat.km, base.latitude = scatter$lat) %>% as.vector()
scatter$add.long.deg <- km2d(scatter$add.long.km, base.latitude = scatter$lat) %>% as.vector()

scatter$latscat <- scatter$lat + scatter$add.lat.deg 
scatter$longscat <- scatter$long + scatter$add.long.deg

# round
scatter$latscat <- round(scatter$latscat, 1)
scatter$longscat <- round(scatter$longscat, 1)

scatter.sf <- scatter %>% st_as_sf(., coords = c("long", "lat"), crs = 4326)
coords.scatter <- scatter.sf %>% st_coordinates(extract())

scatter.sf2 <- scatter %>% st_as_sf(., coords = c("longscat", "latscat"), crs = 4326)
coords.scatter2 <- scatter.sf2 %>% st_coordinates(extract())

ggplot() +
  geom_hdr(data = scatter.sf2, aes(x = coords.scatter2[,1], y = coords.scatter2[,2]),
           xlim = c(0,250),
           method = "kde",
           probs = seq(from = 0.1, to = 0.95, length.out = 8)) +
  geom_point(data = scatter.sf,
             aes(x = coords.scatter[,1], y = coords.scatter[,2]), 
             size = 1.1, shape = 21, alpha = 0.9, stroke = 1.9) +
  geom_point(data = scatter.sf2,
             aes(x = coords.scatter2[,1], y = coords.scatter2[,2]), 
             size = 1.1, shape = 21, alpha = 0.9, stroke = 1.9, colour = "red") +
  geom_sf(data = mapWorld, fill = "#EBE3D5", color = NA) +
  geom_sf(data = mapCoast, linewidth = 0.15) +
  coord_sf(xlim = c(46.5, 255),
           ylim = c(-30, 30)) +
  theme_classic() +
  geom_segment(aes(x = 36.2, xend = 36.2, y = -30.1, yend = 30.1), linewidth = 0.8) +
  geom_segment(aes(x = 49.9, xend = 250.1, y = -33, yend = -33), linewidth = 0.8) +
  theme(
    axis.title = element_blank(),
    axis.line = element_blank(),
    axis.text = element_text(size = 11),
    axis.ticks = element_line(linewidth = 0.8),
    title = element_text(size = 13),
    legend.position = "none")



grid <- data.frame(matrix(ncol = length(seq(from = 46.5, to = 255, by = 0.1)),
                          nrow = length(seq(from = -30, to = 30, by = 0.1))))

colnames(grid) <- seq(from = 46.5, to = 255, by = 0.1)
grid$lat <- seq(from = -30, to = 30, by = 0.1)

grid <- replace(grid, is.na(grid), 0)

grid.longer <- grid %>% pivot_longer(!lat,
                                   names_to = "long",
                                   values_to = "count") %>% as.data.frame()
grid.longer$long <- as.numeric(grid.longer$long)



grid.longer <- grid.longer %>% mutate(count = ifelse(lat == 0.9 & long == 172.3, 
                                                     count+1, 
                                                     count))


```

